---
title: "colourmatrix"
author: "Davide Lorino"
date: "20/05/2019"
output: 
  html_document:
    keep_md: true
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true 
    toc_depth: 3
    number_sections: true 
    theme: darkly
    highlight: zenburn
    df_print: paged
---

```{r echo=FALSE}
library(rmarkdown)
library(shiny)
library(packrat)
```

# Main Function

```{c eval=FALSE}

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "accounts.h"
#include "ColourMatrix.h"



user_t user[100];
int number_of_users = 0;
void print_menu (void);                                           /* Print menu       */

/* MAIN -----------------------------------------------------------------------------------------------------------------------------|
 *                                                                                                                                   |    
 */
  

int main(){
  printf(KNRM);                                                   /* Set colour palette to normal */
  float* new_matrix;                                              /* Initialise a matrix object   */

  char chosen_option_char[10], chosen_user_option_char[10];       /* Read string, store in here   */
  int chosen_option, chosen_user_option;                          /* Convert string to int        */
  int rows_example = 0;                                           /* Main func rows variable      */
  int cols_example = 0;                                           /* Main func cols variable      */
  int* rows1 = &rows_example;                                     /* Pointer to rows              */
  int* cols1 = &cols_example;                                     /* Pointer to cols              */
  user_t user[100];
  int logged_in = 0;               
  
  number_of_users = load_users_from_file(user);

  
while(logged_in == 0){   
  
  user_menu();
  
  scanf("%s", chosen_user_option_char);
  chosen_user_option = atoi(&chosen_user_option_char[0]);
  
  if(chosen_user_option == 1 ||
     chosen_user_option == 2){
    if(chosen_user_option == 1){
      create_user(user, number_of_users);
      save_users_to_db(user, number_of_users);
      number_of_users++;
    }
    else if(chosen_user_option == 2){
      user_login(user, number_of_users);
      logged_in = 1;
    }
  }
}

printf("Login Successful\n");
  
  while(1){
  print_menu();                                                   
  
  scanf("%s", chosen_option_char);
  chosen_option = atoi(&chosen_option_char[0]);
  if(chosen_option == 1 ||
     chosen_option == 2 ||
     chosen_option == 3 ||
     chosen_option == 4 ||
     chosen_option == 5 ){
    if(chosen_option == 1){
      new_matrix = create_matrix(rows1, cols1);
    }
    else if(chosen_option == 2){
      printMatrix(new_matrix, rows1, cols1);
    }
    else if(chosen_option == 5){
         deleteMatrix(new_matrix);
        return 0;
      }
    else{
      printf("Invalid choice\n");
      }
   }
}
return 0;
}
  
/* FUNCTIONS ---------------------------------------------------------------------------------------------------------------------------|
 *                                                                                                                                      |
 */

void print_menu (void)
{
  printf("\n"
           "1. add a matrix\n"
           "2. print a matrix\n"
           "3. save matrix\n"
           "4. load matrix\n"
           "5. exit the program\n"
           "Enter choice (number between 1-5)>\n");
}


/*

float mean(float *ptr, int length){
  float sum, mean;
  int i;
  
  for(i = 0; i < length; i++){
    sum = sum + ptr[i];
  }
  
  mean = sum / (i + 1);
  
  printf("The mean is %.2lf", mean);
  
  return mean;  
}

 */
```

# Header Files

## Matrix

Below is the `ColourMatrix.h` header file for matrix creation, manipulation, display and delete

```{c eval=FALSE}
/*
 *          Matrix Manipulation Header File for:
 *          Programming Fundamentals with C Assessment Task 3 - Group Assessment 
 * 
 *          ColourMatrix.h
 */


/* List of font and background colour combinations used by printMatrix */
#define KNRM  "\x1B[0m"
#define KRED  "\x1B[37;41m"
#define KGRN  "\x1B[37;42m"
#define KYEL  "\x1B[37;43m"
#define KBLU  "\x1B[37;44m"
#define KMAG  "\x1B[37;45m"
#define KCYN  "\x1B[37;46m" 
#define KWHT  "\x1B[30;47m"

/* Name of the db file */
#define DB_NAME "db.txt"


/* Creates a matrix by returning a 2d array of the dimensions matrix[rows1][cols1]
 * 
 * This function asks for user input for number of rows and columns, then returns a 2d array of matching dimensions.
 * 
 * rows1 and cols1 are int* values that get updated and are used by other functions such as printMatrix
 */ 
extern float* create_matrix(int * cols1, int* rows1);                    

/* Frees any allocated memory for the supplied matrix */
extern int deleteMatrix(float * mtx);

/* Uses a nested loop to cycle through each row and column, printing each value as it goes
 * 
 * Before landing on the value it is about to print, this function changes the background colour and font colour (there are 8 colour combinations
 * that it cycles through)
 */ 
extern int printMatrix(float * our_matrix, int* rows1, int* cols1);   
```

## Accounts

Below is the `accounts.h` header file for managing user accounts and login

```{c eval=FALSE}

/*
 *      accounts.h
 * 
 *      User account management header file for:
 *      Fundamentals of Programming with C Assignment 3 - Group Assignment
 * 
 */



/* The file name of the database that stores username and password of all accounts */
#define DB_NAME "db.txt"

/* Maximum number of users that can have an account */
#define MAX_NUM_USERS 200

/* The struct that contains all user accounts - to be used as a struct array i.e user[MAX_NUM_USERS] */
struct user {
  char username[50];
  char password[50];
}; 
typedef struct user user_t;


/* Creates a new user account.
 * 
 * Takes the user_t user struct array created at runtime and the int number_of_users (a variable in the main).
 * 
 * First asks for user input of username and password (reads as string, blocks echo of password insertion), then creates 
 * a new user account at the array address pointed to by user[number_of_users]
 * 
 * number_of_users is a runtime variable in the main function that increments upon creation of a new user account and 
 * after loading users from the db file
 */ 
extern void create_user(user_t* user, int number_of_users);


/* Logs a user in.
 * 
 * 1. Takes the user_t user struct array created at runtime and the int number_of_users (a variable in the main).
 * 
 * 2. Asks for user input of username, accepts a string, then stores into a char array: char temp_user[50]
 * 
 * 3. Loops over the user_t user struct array created at runtime. Using string.h::strcmp to determine if the username provided
 * matches any usernames on-file. If it matches, the message Username Matched is printed and it moves on to asking for a password.
 * If the username input doesnt match an existing username, the message username does not exist - create a new account?
 * is printed, giving the user a choice of 1. trying their username again or 2. creating a new account.
 * 
 * 4. Asks for user input of a password. Echo is turned off via system call "stty -echo" to hide user input of password from the terminal/stdout
 * Accepts as string and stores into a char array: char temp_password[50]
 * 
 * 5. Loops over the user_t user struct array created at runtime. Using string.h::strcmp to determine if the password provided
 * matches any passwords on-file. If it matches, the message Login Successful is displayed to the user and the program menu initiates. 
 * If the password input doesnt match an existing password, the message Login Unsuccessful - Try again? appears, giving the user the option to
 * try their username and password again, cretae a new account, or exit the program.
 */ 
extern void user_login(user_t* user, int number_of_users);


/* Saves the username and password of all user accounts to a database file.
 * 
 * Prints each element of the user_t user struct array (username and password) to the db file for storage.
 */ 
extern void save_users_to_db(user_t* user, int number_of_users);


/* Loads all users from the db file into the user_t user struct array on program startup. */
extern int load_users_from_file(user_t* user);


/* First level menu of the program */

extern void user_menu (void);
```


# Implementation Files 

## Matrix

Below is the `ColourMatrix.c` implementation file for matrix creation, manipulation, display and delete

```{c eval=FALSE}
/*
 *          Matrix Manipulation Implementation File for:
 *          Programming Fundamentals with C Assessment Task 3 - Group Assessment 
 * 
 *          ColourMatrix.c
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define assert(ignore) ((void)0)

/* List of font and background colour combinations used by printMatrix */
#define KNRM  "\x1B[0m"
#define KRED  "\x1B[37;41m"
#define KGRN  "\x1B[37;42m"
#define KYEL  "\x1B[37;43m"
#define KBLU  "\x1B[37;44m"
#define KMAG  "\x1B[37;45m"
#define KCYN  "\x1B[37;46m" 
#define KWHT  "\x1B[30;47m"

/* Name of the db file */
#define DB_NAME "db.txt"


/* Frees any allocated memory for the supplied matrix */
int deleteMatrix(float * mtx) {
  if (!mtx) return -1;
  /* free mtxs data */
  assert (mtx);
  free(mtx);
  mtx = NULL;
  return 0;
}


/* Uses a nested loop to cycle through each row and column, printing each value as it goes
 * 
 * Before landing on the value it is about to print, this function changes the background colour and font colour (there are 8 colour combinations
 * that it cycles through)
 */ 
int printMatrix(float * our_matrix, int * rows1, int * cols1) {
  int counter = 0;
  int row = 0, col = 0;
  for (col = 1; col <= *cols1; col++) {
    for (row = 1; row <= *rows1; row++) {
      counter++;
      if(counter == 1 || counter % 8 == 1)                              /* This bit sets the colour of the printer */
  printf(KRED);
      else if(counter == 2 || counter % 8 == 2) 
        printf(KGRN);
      else if(counter == 3 || counter % 8 == 3)
        printf(KYEL);
      else if(counter == 4 || counter % 8 == 4)
        printf(KBLU);
      else if(counter == 5 || counter % 8 == 5)
        printf(KMAG);
      else if(counter == 6 || counter % 8 == 6)
        printf(KCYN);
      else if(counter == 7 || counter % 8 == 7)
        printf(KWHT);
      else if(counter == 8 || counter % 8 == 0)
        printf(KNRM);
      
      printf(" %2.f ", *our_matrix+(col-1)+(row-1));                /* This line prints the corresponding row+col of the nested loop */
    }
    /* separate rows by newlines */
    printf("\n");
  }
  printf(KNRM);                                                         /* Set colour back to normal */
    return 0;
}


/* Creates a matrix by returning a 2d array of the dimensions matrix[rows1][cols1]
 * 
 * This function asks for user input for number of rows and columns, then returns a 2d array of matching dimensions.
 * 
 * rows1 and cols1 are int* values that get updated and are used by other functions such as printMatrix
 */ 

float* create_matrix(int * cols1, int* rows1){
  
  int rows, cols;
  
  printf("Enter the number of rows>\n");
  scanf("%d", &rows);
  
  printf("Enter the number of cols>\n");
  scanf("%d", &cols);
  
  float * our_matrix = (float *) malloc(rows * cols * sizeof(float));
  
  *cols1 = cols;
  *rows1 = rows;
  
  return our_matrix;
  
}
```

## Accounts

Below is the implementation file `accounts.c` for managing user accounts and login

```{c eval=FALSE}
/*        
 *        User Account Management Implementation File:
 *        accounts.c
 * 
 *        Fundamentals of Programming with C Assessment Task 3 - Group Assignment
 */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* The file name of the database that stores username and password of all accounts */
#define DB_NAME "db.txt"

/* Maximum number of users that can have an account */
#define MAX_NUM_USERS 200

/* The struct that contains all user accounts - to be used as a struct array i.e user[MAX_NUM_USERS] */
struct user {
  char username[50];
  char password[50];
}; 
typedef struct user user_t;


/* Creates a new user account.
 * 
 * Takes the user_t user struct array created at runtime and the int number_of_users (a variable in the main).
 * 
 * First asks for user input of username and password (reads as string, blocks echo of password insertion), then creates 
 * a new user account at the array address pointed to by user[number_of_users]
 * 
 * number_of_users is a runtime variable in the main function that increments upon creation of a new user account and 
 * after loading users from the db file
 */ 
void create_user(user_t* user, int number_of_users){
  char dont_print[20];
  char do_print[20];
  char temp_username[50];
  
  strcpy(dont_print, "stty -echo");
  strcpy(do_print, "stty echo");
  
  
  
  
  printf("Enter a username>\n");
  fgetc(stdin);
  scanf("%s", temp_username);
  
  
  strcpy((user+number_of_users)->username, temp_username);
  
  printf("Enter a password\n");
  system(dont_print);
  scanf("%s", (user+number_of_users)->password);
  system(do_print);
  
}



/* Logs a user in.
 * 
 * 1. Takes the user_t user struct array created at runtime and the int number_of_users (a variable in the main).
 * 
 * 2. Asks for user input of username, accepts a string, then stores into a char array: char temp_user[50]
 * 
 * 3. Loops over the user_t user struct array created at runtime. Using string.h::strcmp to determine if the username provided
 * matches any usernames on-file. If it matches, the message "Username Matched" is printed and it moves on to asking for a password.
 * If the username input doesnt match an existing username, the message "username does not exist - create a new account?"
 * is printed, giving the user a choice of 1. trying their username again or 2. creating a new account.
 * 
 * 4. Asks for user input of a password. Echo is turned off via system call "stty -echo" to hide user input of password from the terminal/stdout
 * Accepts as string and stores into a char array: char temp_password[50]
 * 
 * 5. Loops over the user_t user struct array created at runtime. Using string.h::strcmp to determine if the password provided
 * matches any passwords on-file. If it matches, the message "Login Successful" is displayed to the user and the program menu initiates. 
 * If the password input doesnt match an existing password, the message "Login Unsuccessful - Try again?" appears, giving the user the option to
 * try their username and password again, cretae a new account, or exit the program.
 */ 
void user_login(user_t* user, int number_of_users){
  char dont_print[20];
  char do_print[20];
  char username_input[50];
  char password_input[50];
  int i, username_not_matched = 1, password_not_matched = 1;
  strcpy(dont_print, "stty -echo");
  strcpy(do_print, "stty echo");
  
  while(username_not_matched == 1){
    
    printf("Enter your username:\n");
    scanf("%s", username_input);
    
    for(i = 0; i < number_of_users; i++){
      if(!strcmp(username_input, user[i].username)){
        username_not_matched = 0;
      } 
    } 
  }
  
  printf("Username matched\n");
  
  while(password_not_matched == 1){
    printf("Enter your password:\n");
    
    system(dont_print);
    fgetc(stdin);
    scanf("%s", password_input);
    system(do_print);
    
    for(i = 0; i < number_of_users; i++){
      if(!strcmp(password_input, user[i].password)){
        password_not_matched = 0;
      } 
    }
  }
}



/* Saves the username and password of all user accounts to a database file.
 * 
 * Prints each element of the user_t user struct array (username and password) to the db file for storage.
 */ 
void save_users_to_db(user_t* user, int number_of_users){
  FILE* fp;
  int i;
  
  fp = fopen(DB_NAME, "w");
  
  for(i = 0; i <= number_of_users; i++){
    fprintf(fp, "%s %s\n",
            user[i].username,
            user[i].password);
  }
  fclose (fp);
}


/* Loads all users from the db file into the user_t user struct array on program startup. */
int load_users_from_file(user_t* user){
  int data_counter;
  data_counter = 0;
  FILE *input = fopen(DB_NAME, "r");
  while(fscanf(input, "%s %s", 
               (user+data_counter)->username,
               (user+data_counter)->password) != EOF){
    data_counter++;
    printf("%i loaded users\n", data_counter);
  }
  fclose(input);
  return data_counter;
}



/* First level menu of the program */

void user_menu (void)
{
  printf("\n"
           "1. Create new user\n"
           "2. Login\n"
           "Enter choice>\n");
}
```

# Bugs & Corner Cases

Currently there are a list known bugs and corner cases in feature implementation that need to be fixed. The list of known bugs and unaddressed corner cases is as follows:

* `create_user()` function from `accounts.h` does not check the `user_t user` struct for already-existing usernames
* `save_users_to_db` does not encrypt username or password information, and outputs the file as .txt which is a serious security flaw
* compiling on linux reveals a memory bug that affects the first print of a matrix under a new user account but no further print attempts

<style>
 pre, code {
color: #FFFFFF;
background-color: #000000;
}
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>




